Python 3.14: handle `typing.Union` immutability
Attempting to [publish an experimental project](https://github.com/ncoghlan/tstrprocess/actions/runs/14682311907/job/41206490424#step:3:76) that will require Python 3.14's t-strings to run, I encountered the following exception from this code:

```
AttributeError: 'typing.Union' object has no attribute '__module__' and no __dict__ for setting new attributes. Did you mean: '__reduce__'?
```

This error is due to `typing.Union` instances becoming immutable in Python 3.14+: https://docs.python.org/3.14/whatsnew/3.14.html#typing

The PR currently works by ignoring the exception raised (since that's the most robust option), but an alternative approach would be to add a `hasattr` check so only values that already have a `__module__` attribute get modified.